services:
  web:
    image: 628253046406.dkr.ecr.ap-south-1.amazonaws.com/diary-backend:cc
    container_name: diary-app
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    # No ports exposed to host; stays private inside the Docker network

  nginx:
    image: nginx:latest
    container_name: diary-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  static_volume:
