name: Terraform Infra

on:
  workflow_dispatch:   # manual only
  push:
    paths:
      - 'terror-infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terror-infra/environments/prod

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::628253046406:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Manual Approval)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan
